require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RoundsController do

  def mock_round(stubs={})
    @mock_round ||= mock_model(Round, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all rounds as @rounds" do
      Round.stub(:all) { [mock_round] }
      get :index
      assigns(:rounds).should eq([mock_round])
    end
  end

  describe "GET show" do
    it "assigns the requested round as @round" do
      Round.stub(:find).with("37") { mock_round }
      get :show, :id => "37"
      assigns(:round).should be(mock_round)
    end
  end

  describe "GET new" do
    it "assigns a new round as @round" do
      Round.stub(:new) { mock_round }
      get :new
      assigns(:round).should be(mock_round)
    end
  end

  describe "GET edit" do
    it "assigns the requested round as @round" do
      Round.stub(:find).with("37") { mock_round }
      get :edit, :id => "37"
      assigns(:round).should be(mock_round)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created round as @round" do
        Round.stub(:new).with({'these' => 'params'}) { mock_round(:save => true) }
        post :create, :round => {'these' => 'params'}
        assigns(:round).should be(mock_round)
      end

      it "redirects to the created round" do
        Round.stub(:new) { mock_round(:save => true) }
        post :create, :round => {}
        response.should redirect_to(round_url(mock_round))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved round as @round" do
        Round.stub(:new).with({'these' => 'params'}) { mock_round(:save => false) }
        post :create, :round => {'these' => 'params'}
        assigns(:round).should be(mock_round)
      end

      it "re-renders the 'new' template" do
        Round.stub(:new) { mock_round(:save => false) }
        post :create, :round => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested round" do
        Round.stub(:find).with("37") { mock_round }
        mock_round.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :round => {'these' => 'params'}
      end

      it "assigns the requested round as @round" do
        Round.stub(:find) { mock_round(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:round).should be(mock_round)
      end

      it "redirects to the round" do
        Round.stub(:find) { mock_round(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(round_url(mock_round))
      end
    end

    describe "with invalid params" do
      it "assigns the round as @round" do
        Round.stub(:find) { mock_round(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:round).should be(mock_round)
      end

      it "re-renders the 'edit' template" do
        Round.stub(:find) { mock_round(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested round" do
      Round.stub(:find).with("37") { mock_round }
      mock_round.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the rounds list" do
      Round.stub(:find) { mock_round }
      delete :destroy, :id => "1"
      response.should redirect_to(rounds_url)
    end
  end

end
